package com.xueyituanchina.xueyituan.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xueyituanchina.xueyituan.mpbe.bean.LocalBean;
import com.xueyituanchina.xueyituan.mpbe.bean.LookWhatBean;

import com.xueyituanchina.xueyituan.greendao.LocalBeanDao;
import com.xueyituanchina.xueyituan.greendao.LookWhatBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localBeanDaoConfig;
    private final DaoConfig lookWhatBeanDaoConfig;

    private final LocalBeanDao localBeanDao;
    private final LookWhatBeanDao lookWhatBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localBeanDaoConfig = daoConfigMap.get(LocalBeanDao.class).clone();
        localBeanDaoConfig.initIdentityScope(type);

        lookWhatBeanDaoConfig = daoConfigMap.get(LookWhatBeanDao.class).clone();
        lookWhatBeanDaoConfig.initIdentityScope(type);

        localBeanDao = new LocalBeanDao(localBeanDaoConfig, this);
        lookWhatBeanDao = new LookWhatBeanDao(lookWhatBeanDaoConfig, this);

        registerDao(LocalBean.class, localBeanDao);
        registerDao(LookWhatBean.class, lookWhatBeanDao);
    }
    
    public void clear() {
        localBeanDaoConfig.clearIdentityScope();
        lookWhatBeanDaoConfig.clearIdentityScope();
    }

    public LocalBeanDao getLocalBeanDao() {
        return localBeanDao;
    }

    public LookWhatBeanDao getLookWhatBeanDao() {
        return lookWhatBeanDao;
    }

}
